# Generated by Django 5.0.3 on 2024-03-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.BooleanField(default=False),
        ),
    ]
