# Generated by Django 5.0.3 on 2024-03-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0002_user_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='country',
            new_name='b_place',
        ),
        migrations.AddField(
            model_name='info',
            name='name',
            field=models.CharField(default=False, max_length=30),
            preserve_default=False,
        ),
    ]
